### ISSUE TITLE
Null Pointer during publication and subscription

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#122]
## Summary

When running the wantest federate I occasionally see the following exceptions generated during the pub/sub stage. I have seen this in both evoked and immediate callback modes. The error is typically repeated a number of times (due to multiple calls to the pub/sub methods).

```
INFO  [main] wantest: 
INFO  [main] wantest:     Test Driver: Latency Test
INFO  [main] wantest:   Callback Mode: EVOKED
INFO  [main] wantest: 
INFO  [main] wantest: Creating RTIambassador
WARN  [main] portico.lrc: MOM support is currently unsupported in IEEE-1516e federations.
INFO  [main] wantest: Connecting...
INFO  [main] wantest: Creating Federation...

-------------------------------------------------------------------
GMS: address=localhost-26110, cluster=WAN Test Federation, physical address=127.0.0.1:65234
-------------------------------------------------------------------
INFO  [main] wantest: Created Federation [WAN Test Federation]
ERROR [ImmediateCallbackDispatcher] portico.lrc: FAILURE Exception encountered while processing incoming message: null
java.lang.NullPointerException
    at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:482)
    at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:443)
    at org.portico.lrc.services.object.data.InterestManager.publishInteractionClass(InterestManager.java:945)
    at org.portico.lrc.services.pubsub.handlers.incoming.PublishInteractionClassIncomingHandler.process(PublishInteractionClassIncomingHandler.java:69)
    at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
    at org.portico.lrc.LRC.tickProcess(LRC.java:688)
    at org.portico.lrc.LRC.access$100(LRC.java:106)
    at org.portico.lrc.LRC$ImmediateCallbackDispatcher.run(LRC.java:834)
```

## Environment and Logs

- Portico 2.0.1
- Test on Mac OS X 10.9

## Reproduction Steps

 - Start a wantest latency test federation with 2-4 federates
 - Some of them, on occasion, will produce the following exceptions

**Comment by bergtwvd** [comment]
I see the same error appearing at different federates when running a Docker multi-container federation:

```
kml_1             | ERROR [main] portico.lrc: FAILURE Exception encountered while processing incoming message: null
kml_1             | java.lang.NullPointerException
kml_1             |     at kmlserver.FederateAmbassador.reflectAttributeValues(FederateAmbassador.java:106)
kml_1             |     at kmlserver.FederateAmbassador.reflectAttributeValues(FederateAmbassador.java:67)
kml_1             |     at org.portico.impl.hla1516e.handlers.ReflectAttributesCallbackHandler.process(ReflectAttributesCallbackHandler.java:102)
kml_1             |     at org.portico.utils.messaging.MessageChain.process(MessageChain.java:78)
kml_1             |     at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
kml_1             |     at org.portico.lrc.LRC.tickProcess(LRC.java:688)
kml_1             |     at org.portico.lrc.LRC.tick(LRC.java:555)
kml_1             |     at org.portico.impl.hla1516e.Impl1516eHelper.evokeMultiple(Impl1516eHelper.java:188)
kml_1             |     at org.portico.impl.hla1516e.Rti1516eAmbassador.evokeMultipleCallbacks(Rti1516eAmbassador.java:5407)
kml_1             |     at kmlserver.Federate.start(Federate.java:323)
kml_1             |     at kmlserver.KMLServer.start(KMLServer.java:116)
kml_1             |     at kmlserver.Main.main(Main.java:248)
kml_1             | ERROR [main] portico.lrc: FAILURE Exception encountered while processing incoming message: null
kml_1             | java.lang.NullPointerException
```

**Comment by timpokorny** [comment]
I have not been able to reproduce this as yet despite running the throughput and latency hpref federates many times (both fully local and over a WAN). Going to close this out as Cannot Reproduce but it may just have been sorted out over the long history since this was first files.
