### ISSUE TITLE
RoleCall error

### ISSUE THREAD

**Issue by hodiapa** [openlvc/portico#161]
I am having issues while federate joining a federation with the RoleCall methods.

I have two Federates: Manager and F1.
Manager and F1 both join the Federation(TestFederation).

Here is the error message one Receives:

```
   ERROR [main] portico.lrc: Waited 5 seconds for RoleCall from federate [1], none received, connection error

   org.portico.lrc.compat.JRTIinternalError: Waited 5 seconds for RoleCall from federate [1], none received, connection error

  at       org.portico.lrc.services.federation.handlers.outgoing.JoinFederationHandler.process(JoinFederationHandler.java:146)
```

Enclosing Complete log

**Comment by hodiapa** [comment]
Here is the log for Federate F1:
      
     portico.log 9bf6:/usr/local/portico/portico-2.0.1/examples/java/hla13/logs# cat                                                                                                                                                                       
DEBUG [main] portico.lrc: Creating new LRC                                                                                                                                                                                                             
DEBUG [main] portico.lrc: Portico version: 2.0.1 (build 0)                                                                                                                                                                                             
DEBUG [main] portico.lrc: Interface: HLA13                                                                                                                                                                                                             
TRACE [main] portico.lrc: Provided connection implementation is "org.portico.bindings.jgroups.JGroupsConnection"                                                                                                                                       
TRACE [main] portico.lrc: Trying to load connection class: org.portico.bindings.jgroups.JGroupsConnection                                                                                                                                              
TRACE [main] portico.lrc: ATTEMPT create IConnection, class= class org.portico.bindings.jgroups.JGroupsConnection                                                                                                                                      
TRACE [main] portico.lrc: SUCCESS created IConnection, class= class org.portico.bindings.jgroups.JGroupsConnection     
      TRACE [main] portico.lrc: STARTING Apply module [lrc-base] to LRC                                                                                                                                                                                      
TRACE [main] portico.lrc: Applied [91/92] handlers                                                                                                                                                                                                     
TRACE [main] portico.lrc: STARTING Apply module [lrc1516-callback] to LRC                                                                                                                                                                              
TRACE [main] portico.lrc: Applied [0/11] handlers                                                                                                                                                                                                      
TRACE [main] portico.lrc: STARTING Apply module [lrc13-callback] to LRC                                                                                                                                                                                
TRACE [main] portico.lrc: Applied [24/24] handlers                                                                                                                                                                                                     
TRACE [main] portico.lrc: STARTING Apply module [lrc1516e-callback] to LRC                                                                                                                                                                             
TRACE [main] portico.lrc: Applied [0/24] handlers                                                                                                                                                                                                      
DEBUG [main] portico.lrc: Messaging framework configuration complete                                                                                                                                                                                   
INFO  [main] portico.lrc: LRC initialized (HLA version: HLA13)                                                                                                                                                                                         
INFO  [main] portico.lrc: Opening LRC Connection                                                                                                                                                                                                       
INFO  [main] portico.lrc.jgroups: jgroups connection is up and running                                                                                                                                                                                 
DEBUG [main] portico.lrc.fom: Parsing FED file (format=hla13): file:/usr/local/portico/portico-2.0.1/examples/java/hla13/testfom.fed                                                                                                                   
DEBUG [main] portico.lrc: ATTEMPT Create federation execution [TestFederation]                                                                                                                                                                       
TRACE [main] portico.lrc.jgroups: ATTEMPT Connecting to channel [TestFederation]                                                                                                                                                                     
DEBUG [main] org.jgroups.conf.ClassConfigurator: Using jg-magic-map.xml as magic number file and jg-protocol-ids.xml for protocol IDs                                                                                                                  
DEBUG [main] org.jgroups.stack.Configurator: set property UDP.bind_addr to default value /172.17.0.30                                                                                                                                                  
DEBUG [main] org.jgroups.stack.Configurator: set property UDP.diagnostics_addr to default value /224.0.75.75                                                                                                                                           
DEBUG [main] org.jgroups.protocols.FRAG2: received CONFIG event: {bind_addr=/172.17.0.30}                                                                                                                                                              
DEBUG [main] org.jgroups.protocols.FRAG2: received CONFIG event: {flush_supported=true}                                                                                                                                                                
DEBUG [main] org.jgroups.protocols.UDP: sockets will use interface 172.17.0.30                                                                                                                                                                         
WARN  [main] org.jgroups.protocols.UDP: [JGRP00014] the send buffer of socket DatagramSocket was set to 640KB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. n
et.core.wmem_max on Linux)                                                                                                                                                                                                                             
WARN  [main] org.jgroups.protocols.UDP: [JGRP00014] the receive buffer of socket DatagramSocket was set to 8MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max receive buffer in the OS correctly (e.
g. net.core.rmem_max on Linux)                                                                                                                                                                                                                         
WARN  [main] org.jgroups.protocols.UDP: [JGRP00014] the send buffer of socket MulticastSocket was set to 640KB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. 
net.core.wmem_max on Linux)                                                                                                                                                                                                                            
WARN  [main] org.jgroups.protocols.UDP: [JGRP00014] the receive buffer of socket MulticastSocket was set to 8MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max receive buffer in the OS correctly (e
.g. net.core.rmem_max on Linux)                                                                                                                                                                                                                        
DEBUG [main] org.jgroups.protocols.UDP: socket information: 
      , mcast_addr=239.255.20.16:20913, bind_addr=/172.17.0.30, ttl=8                                                                                                                                                                                        
sock: bound to 172.17.0.30:36870, receive buffer size=212992, send buffer size=212992                                                                                                                                                                  
mcast_sock: bound to 172.17.0.30:20913, send buffer size=212992, receive buffer size=212992                                                                                                                                                            
DEBUG [main] org.jgroups.protocols.pbcast.GMS: election results: {07e3b9349bf6-21744=1}                                                                                                                                                                
DEBUG [main] org.jgroups.protocols.pbcast.GMS: sending JOIN(07e3b9349bf6-10198) to 07e3b9349bf6-21744                                                                                                                                                  
DEBUG [main] org.jgroups.protocols.pbcast.NAKACK2:                                                                                                                                                                                                     
[07e3b9349bf6-10198 setDigest()]                                                                                                                                                                                                                       
existing digest:  []                                                                                                                                                                                                                                   
new digest:       07e3b9349bf6-21744: [523 (523)], 07e3b9349bf6-10198: [0 (0)]                                                                                                                                                                         
resulting digest: 07e3b9349bf6-10198: [0 (0)], 07e3b9349bf6-21744: [523 (523)]                                                                                                                                                                         
DEBUG [main] org.jgroups.protocols.pbcast.GMS: 07e3b9349bf6-10198: installing view [07e3b9349bf6-21744|3] [07e3b9349bf6-21744, 07e3b9349bf6-10198]                                                                                                     
DEBUG [main] org.jgroups.protocols.pbcast.STABLE: [ergonomics] setting max_bytes to 8MB (2 members)                                                                                                                                                    
DEBUG [main] org.jgroups.protocols.pbcast.FLUSH: 07e3b9349bf6-10198: installing view [07e3b9349bf6-21744|3] [07e3b9349bf6-21744, 07e3b9349bf6-10198]                                                                                                   
DEBUG [main] org.jgroups.protocols.pbcast.STATE_TRANSFER: 07e3b9349bf6-10198: asking 07e3b9349bf6-21744 for state                                                                                                                                      
DEBUG [Incoming,TestFederation,07e3b9349bf6-10198] org.jgroups.protocols.pbcast.STATE_TRANSFER: 07e3b9349bf6-10198: received state, size=21.54KB, time=10 milliseconds                                                                               
DEBUG [main] org.jgroups.protocols.pbcast.FLUSH: 07e3b9349bf6-10198: received RESUME, sending STOP_FLUSH to all                                                                                                                                        
DEBUG [Incoming,TestFederation,07e3b9349bf6-10198] org.jgroups.protocols.pbcast.FLUSH: 07e3b9349bf6-10198: received STOP_FLUSH, unblocking FLUSH.down() and sending UNBLOCK up                                                                       
DEBUG [main] portico.lrc.jgroups: SUCCESS Connected to channel [TestFederation]                                                                                                                                                                      
DEBUG [main] portico.lrc.jgroups: REQUEST createFederation: name=TestFederation                                                                                                                                                                      
ERROR [main] portico.lrc.jgroups: FAILURE createFederation: already exists, name=TestFederation                                                                                                                                                      
ERROR [main] portico.lrc: federation exists: TestFederation                                                                                                                                                                                          
org.portico.lrc.compat.JFederationExecutionAlreadyExists: federation exists: TestFederation                                                                                                                                                          
        at org.portico.bindings.jgroups.channel.FederationChannel.createFederation(FederationChannel.java:268)                                                                                                                                         
        at org.portico.bindings.jgroups.JGroupsConnection.createFederation(JGroupsConnection.java:232)                                                                                                                                                 
        at org.portico.lrc.services.federation.handlers.outgoing.CreateFederationHandler.process(CreateFederationHandler.java:79)                                                                                                                      
        at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)                                                                                                                                                                       
        at org.portico.impl.hla13.Impl13Helper.processMessage(Impl13Helper.java:123)                                                                                                                                                                   
        at org.portico.impl.hla13.Rti13Ambassador.processMessage(Rti13Ambassador.java:5822)                                                                                                                                                            
        at org.portico.impl.hla13.Rti13Ambassador.createFederationExecution(Rti13Ambassador.java:194)                                                                                                                                                  
        at hla13.Example13Federate.runFederate(Example13Federate.java:184)
        at hla13.Example13Federate.main(Example13Federate.java:563)                                                                                                                                                                                    
DEBUG [main] portico.lrc: ATTEMPT Join federate [F1] to federation [TestFederation]                                                                                                                                                                  
DEBUG [main] portico.lrc.jgroups: Validate that [0] modules can merge successfully with the existing FOM                                                                                                                                               
DEBUG [main] portico.lrc.jgroups: Modules can be merged successfully, continue with join                                                                                                                                                               
DEBUG [main] portico.lrc.jgroups: REQUEST joinFederation: federate=F1, federation=TestFederation                                                                                                                                                     
TRACE [Incoming,TestFederation,07e3b9349bf6-10198] portico.lrc.jgroups: (incoming) asynchronous, channel=TestFederation, size=2, source=07e3b9349bf6-10198                                                                                         
DEBUG [Incoming,TestFederation,07e3b9349bf6-10198] portico.lrc.jgroups: Received federate join notification: federate=F1, federation=TestFederation, source=07e3b9349bf6-10198                                                                     
INFO  [Incoming,TestFederation,07e3b9349bf6-10198] portico.lrc.jgroups: Federate [F1] joined federation [TestFederation]                                                                                                                           
INFO  [main] portico.lrc.jgroups: SUCCESS Joined federation with name=F1                                                                                                                                                                               
TRACE [main] portico.lrc: Created Mom.Federation object, added to Repository (undiscovered)                                                                                                                                                            
TRACE [main] portico.lrc: Created Mom.Federate(F1), queued discovery notification                                                                                                                                                                      
TRACE [main] portico.lrc.jgroups: (outgoing) payload=RoleCall, size=547, channel=TestFederation                                                                                                                                                      
TRACE [main] portico.lrc: joined federation, waiting for RoleCalls from [1, 2]                                                                                                                                                                         
TRACE [Incoming,TestFederation,07e3b9349bf6-10198] portico.lrc.jgroups: (incoming) asynchronous, channel=TestFederation, size=547, source=07e3b9349bf6-10198                                                                                       
ERROR [main] portico.lrc: Waited 5 seconds for RoleCall from federate [1], none received, connection error                                                                                                                                             
org.portico.lrc.compat.JRTIinternalError: Waited 5 seconds for RoleCall from federate [1], none received, connection error                                                                                                                             
        at org.portico.lrc.services.federation.handlers.outgoing.JoinFederationHandler.process(JoinFederationHandler.java:146)                                                                                                                         
        at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)                                                                                                                                                                       
        at org.portico.impl.hla13.Impl13Helper.processMessage(Impl13Helper.java:123)                                                                                                                                                                   
        at org.portico.impl.hla13.Rti13Ambassador.processMessage(Rti13Ambassador.java:5822)                                                                                                                                                            
        at org.portico.impl.hla13.Rti13Ambassador.joinFederationExecution(Rti13Ambassador.java:321)                                                                                                                                                    
        at hla13.Example13Federate.runFederate(Example13Federate.java:204)                                                                                                                                                                             
        at hla13.Example13Federate.main(Example13Federate.java:563)                                                                                                                                                                                    
DEBUG [main] portico.lrc: Creating new LRC                                                                                                                                                                                                             
DEBUG [main] portico.lrc: Portico version: 2.0.1 (build 0)                                                                                                                                                                                             
DEBUG [main] portico.lrc: Interface: HLA13                                                                                                                                                                                                             
TRACE [main] portico.lrc: Provided connection implementation is "org.portico.bindings.jgroups.JGroupsConnection"                                                                                                                                       
TRACE [main] portico.lrc: Trying to load connection class: org.portico.bindings.jgroups.JGroupsConnection                                                                                                                                              
TRACE [main] portico.lrc: ATTEMPT create IConnection, class= class org.portico.bindings.jgroups.JGroupsConnection                                                                                                                                      
TRACE [main] portico.lrc: SUCCESS created IConnection, class= class org.portico.bindings.jgroups.JGroupsConnection  
TRACE [main] portico.lrc: STARTING Apply module [lrc-base] to LRC                                                                                                                                                                                      
TRACE [main] portico.lrc: Applied [91/92] handlers                                                                                                                                                                                                     
TRACE [main] portico.lrc: STARTING Apply module [lrc13-callback] to LRC                                                                                                                                                                                
TRACE [main] portico.lrc: Applied [24/24] handlers                                                                                                                                                                                                     
DEBUG [main] portico.lrc: Messaging framework configuration complete                                                                                                                                                                                   
INFO  [main] portico.lrc: LRC initialized (HLA version: HLA13)                                                                                                                                                                                         
INFO  [main] portico.lrc: Opening LRC Connection                                                                                                                                                                                                       
INFO  [main] portico.lrc.jgroups: jgroups connection is up and running                                                                                                                                                                                 
DEBUG [main] portico.lrc.fom: Parsing FED file (format=hla13): file:/usr/local/portico/portico-2.0.1/examples/java/hla13/testfom.fed                                                                                                                   
DEBUG [main] portico.lrc: ATTEMPT Create federation execution [TestFederation]                                                                                                                                                                       
TRACE [main] portico.lrc.jgroups: ATTEMPT Connecting to channel [TestFederation]                                                                                                                                                                     
DEBUG [main] org.jgroups.conf.ClassConfigurator: Using jg-magic-map.xml as magic number file and jg-protocol-ids.xml for protocol IDs                                                                                                                  
DEBUG [main] org.jgroups.stack.Configurator: set property UDP.bind_addr to default value /172.17.0.30                                                                                                                                                  
DEBUG [main] org.jgroups.stack.Configurator: set property UDP.diagnostics_addr to default value /224.0.75.75                                                                                                                                           
DEBUG [main] org.jgroups.protocols.FRAG2: received CONFIG event: {bind_addr=/172.17.0.30}                                                                                                                                                              
DEBUG [main] org.jgroups.protocols.FRAG2: received CONFIG event: {flush_supported=true}                                                                                                                                                                
DEBUG [main] org.jgroups.protocols.UDP: sockets will use interface 172.17.0.30                                                                                                                                                                         
WARN  [main] org.jgroups.protocols.UDP: [JGRP00014] the send buffer of socket DatagramSocket was set to 640KB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. n
et.core.wmem_max on Linux)                                                                                                                                                                                                                             
WARN  [main] org.jgroups.protocols.UDP: [JGRP00014] the receive buffer of socket DatagramSocket was set to 8MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max receive buffer in the OS correctly (e.
g. net.core.rmem_max on Linux)                                                                                                                                                                                                                         
WARN  [main] org.jgroups.protocols.UDP: [JGRP00014] the send buffer of socket MulticastSocket was set to 640KB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. 
net.core.wmem_max on Linux)                                                                                                                                                                                                                            
WARN  [main] org.jgroups.protocols.UDP: [JGRP00014] the receive buffer of socket MulticastSocket was set to 8MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max receive buffer in the OS correctly (e
.g. net.core.rmem_max on Linux)  

WARN  [main] org.jgroups.protocols.UDP: [JGRP00014] the send buffer of socket MulticastSocket was set to 640KB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. 
net.core.wmem_max on Linux)                                                                                                                                                                                                                            
WARN  [main] org.jgroups.protocols.UDP: [JGRP00014] the receive buffer of socket MulticastSocket was set to 8MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max receive buffer in the OS correctly (e
.g. net.core.rmem_max on Linux)                                                                                                                                                                                                                        
DEBUG [main] org.jgroups.protocols.UDP: socket information:                                                                                                                                                                                            
, mcast_addr=239.255.20.16:20913, bind_addr=/172.17.0.30, ttl=8                                                                                                                                                                                        
sock: bound to 172.17.0.30:59395, receive buffer size=212992, send buffer size=212992                                                                                                                                                                  
mcast_sock: bound to 172.17.0.30:20913, send buffer size=212992, receive buffer size=212992                                                                                                                                                            
DEBUG [main] org.jgroups.protocols.pbcast.GMS: election results: {07e3b9349bf6-62923=1}                                                                                                                                                                
DEBUG [main] org.jgroups.protocols.pbcast.GMS: sending JOIN(07e3b9349bf6-24659) to 07e3b9349bf6-62923                                                                                                                                                  
DEBUG [main] org.jgroups.protocols.pbcast.NAKACK2:                                                                                                                                                                                                     
[07e3b9349bf6-24659 setDigest()]                                                                                                                                                                                                                       
existing digest:  []                                                                                                                                                                                                                                   
new digest:       07e3b9349bf6-62923: [20 (20)], 07e3b9349bf6-24659: [0 (0)]                                                                                                                                                                           
resulting digest: 07e3b9349bf6-24659: [0 (0)], 07e3b9349bf6-62923: [20 (20)]                                                                                                                                                                           
DEBUG [main] org.jgroups.protocols.pbcast.GMS: 07e3b9349bf6-24659: installing view [07e3b9349bf6-62923|1] [07e3b9349bf6-62923, 07e3b9349bf6-24659]                                                                                                     
DEBUG [main] org.jgroups.protocols.pbcast.STABLE: [ergonomics] setting max_bytes to 8MB (2 members)                                                                                                                                                    
DEBUG [main] org.jgroups.protocols.pbcast.FLUSH: 07e3b9349bf6-24659: installing view [07e3b9349bf6-62923|1] [07e3b9349bf6-62923, 07e3b9349bf6-24659]                                                                                                   
DEBUG [main] org.jgroups.protocols.pbcast.STATE_TRANSFER: 07e3b9349bf6-24659: asking 07e3b9349bf6-62923 for state                                                                                                                                      
DEBUG [Incoming,TestFederation,07e3b9349bf6-24659] org.jgroups.protocols.pbcast.STATE_TRANSFER: 07e3b9349bf6-24659: received state, size=21.54KB, time=15 milliseconds                                                                               
DEBUG [main] org.jgroups.protocols.pbcast.FLUSH: 07e3b9349bf6-24659: received RESUME, sending STOP_FLUSH to all                                                                                                                                        
DEBUG [main] portico.lrc.jgroups: SUCCESS Connected to channel [TestFederation]                                                                                                                                                                      
DEBUG [main] portico.lrc.jgroups: REQUEST createFederation: name=TestFederation                                                                                                                                                                      
ERROR [main] portico.lrc.jgroups: FAILURE createFederation: already exists, name=TestFederation                                                                                                                                                      
DEBUG [Incoming,TestFederation,07e3b9349bf6-24659] org.jgroups.protocols.pbcast.FLUSH: 07e3b9349bf6-24659: received STOP_FLUSH, unblocking FLUSH.down() and sending UNBLOCK up                                                                       
ERROR [main] portico.lrc: federation exists: TestFederation                                                                                                                                                                                          
org.portico.lrc.compat.JFederationExecutionAlreadyExists: federation exists: TestFederation 
      at org.portico.lrc.services.federation.handlers.outgoing.CreateFederationHandler.process(CreateFederationHandler.java:79)                                                                                                                      
        at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)                                                                                                                                                                       
        at org.portico.impl.hla13.Impl13Helper.processMessage(Impl13Helper.java:123)                                                                                                                                                                   
        at org.portico.impl.hla13.Rti13Ambassador.processMessage(Rti13Ambassador.java:5822)                                                                                                                                                            
        at org.portico.impl.hla13.Rti13Ambassador.createFederationExecution(Rti13Ambassador.java:194)                                                                                                                                                  
        at hla13.Example13Federate.runFederate(Example13Federate.java:184)                                                                                                                                                                             
        at hla13.Example13Federate.main(Example13Federate.java:563)                                                                                                                                                                                    
DEBUG [main] portico.lrc: ATTEMPT Join federate [F1] to federation [TestFederation]                                                                                                                                                                  
DEBUG [main] portico.lrc.jgroups: Validate that [0] modules can merge successfully with the existing FOM                                                                                                                                               
DEBUG [main] portico.lrc.jgroups: Modules can be merged successfully, continue with join                                                                                                                                                               
DEBUG [main] portico.lrc.jgroups: REQUEST joinFederation: federate=F1, federation=TestFederation                                                                                                                                                     
TRACE [Incoming,TestFederation,07e3b9349bf6-24659] portico.lrc.jgroups: (incoming) asynchronous, channel=TestFederation, size=2, source=07e3b9349bf6-24659                                                                                         
DEBUG [Incoming,TestFederation,07e3b9349bf6-24659] portico.lrc.jgroups: Received federate join notification: federate=F1, federation=TestFederation, source=07e3b9349bf6-24659                                                                     
INFO  [Incoming,TestFederation,07e3b9349bf6-24659] portico.lrc.jgroups: Federate [F1] joined federation [TestFederation]                                                                                                                           
INFO  [main] portico.lrc.jgroups: SUCCESS Joined federation with name=F1                                                                                                                                                                               
TRACE [main] portico.lrc: Created Mom.Federation object, added to Repository (undiscovered)                                                                                                                                                            
TRACE [main] portico.lrc: Created Mom.Federate(F1), queued discovery notification                                                                                                                                                                      
TRACE [main] portico.lrc.jgroups: (outgoing) payload=RoleCall, size=547, channel=TestFederation                                                                                                                                                      
TRACE [main] portico.lrc: joined federation, waiting for RoleCalls from [1, 2]                                                                                                                                                                         
TRACE [Incoming,TestFederation,07e3b9349bf6-24659] portico.lrc.jgroups: (incoming) asynchronous, channel=TestFederation, size=547, source=07e3b9349bf6-24659                                                                                       
ERROR [main] portico.lrc: Waited 5 seconds for RoleCall from federate [1], none received, connection error                                                                                                                                             
org.portico.lrc.compat.JRTIinternalError: Waited 5 seconds for RoleCall from federate [1], none received, connection error                                                                                                                             
        at org.portico.lrc.services.federation.handlers.outgoing.JoinFederationHandler.process(JoinFederationHandler.java:146)                                                                                                                         
        at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)                                                                                                                                                                       
        at org.portico.impl.hla13.Impl13Helper.processMessage(Impl13Helper.java:123)                                                                                                                                                                   
        at org.portico.impl.hla13.Rti13Ambassador.processMessage(Rti13Ambassador.java:5822)                                                                                                                                                            
        at org.portico.impl.hla13.Rti13Ambassador.joinFederationExecution(Rti13Ambassador.java:321)                                                                                                                                                    
        at hla13.Example13Federate.runFederate(Example13Federate.java:204)                                                                                                                                                                             
        at hla13.Example13Federate.main(Example13Federate.java:563)

**Comment by hodiapa** [comment]
Debug Log For the Federate Manager:

INFO: Waiting for "F1" federate to join ...                                                                                                                                                                                                          
DEBUG [Incoming,TestFederation,07e3b9349bf6-62923] portico.lrc.jgroups: Received federate join notification: federate=F1, federation=TestFederation, source=07e3b9349bf6-24659                                                                   
INFO  [Incoming,TestFederation,07e3b9349bf6-62923] portico.lrc.jgroups: Federate [F1] joined federation [TestFederation]                                                                                                                         
DEBUG [Incoming,TestFederation,07e3b9349bf6-62923] portico.lrc: @REMOTE RoleCall received [handle:2,name:F1] by local federate [manager]                                                                                                           
TRACE [Incoming,TestFederation,07e3b9349bf6-62923] portico.lrc: Created Mom.Federate(F1), queued discovery notification                                                                                                                            
TRACE [main] portico.lrc: @REMOTE Received MOM object discovery for federate [MOM.Federate(F1)]                                                                                                                                                      
TRACE [main] portico.lrc: CALLBACK discoverObjectInstance(object=2097151,class=2,name=MOM.Federate(F1))                                                                                                                                              
INFO  [Incoming,TestFederation,07e3b9349bf6-62923] portico.lrc.jgroups: Federate [F1,2] disconnected, synthesizing resign message

**Comment by hodiapa** [comment]
I was able to resolve this issue my telling the application to listen on IPv4 only.

**Comment by timpokorny** [comment]
G'day @hodiapa,

That is interesting! I thought that I was already doing this in the Portico internals, but perhaps it is too late by the time I am setting it.

One other way is to specify the `portico.jgroups.udp.bindAddress` property inside the `RTI.rid` file to be the IP of the NIC you want to use. That will both force it onto that interface and onto the right stack. Currently that properly it not named very well and I'll need to make it a bit clearer and easy to use as this is a common problem. Thank-you for writing back!

**Comment by hodiapa** [comment]
On that front, I did try to include something like:

"portico.jgroups.udp.bindAddress = match-interface:ethwe.*"

But somehow it doesn't work. Here is the exception:
```
caused by: java.lang.Exception: Conversion of bind_addr in UDP with original property value match-interface:ethwe.* failed
	at org.jgroups.conf.PropertyHelper.getConvertedValue(PropertyHelper.java:85)
	at org.jgroups.stack.Configurator.resolveAndAssignField(Configurator.java:1144)
	... 22 more
Caused by: java.net.UnknownHostException: match-interface:ethwe.*
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:922)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1316)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1269)
	at java.net.InetAddress.getAllByName(InetAddress.java:1185)
	at java.net.InetAddress.getAllByName(InetAddress.java:1119)
	at java.net.InetAddress.getByName(InetAddress.java:1069)
	at org.jgroups.conf.PropertyConverters$Default.convert(PropertyConverters.java:257)
	at org.jgroups.conf.PropertyHelper.getConvertedValue(PropertyHelper.java:82)
	... 23 more
```

**Comment by timpokorny** [comment]
Automatic Note: I am cleaning up old Github issues.

If this issue is still impacting you, please re-open the ticket for some hopefully timely attention this time :(

**General Note**
I have been working to try and consolidate the current state of the repo. Specifically, to set up two longer term maintenance branches. I will shortly do two releases off these branches (2.2.0 and 2.1.3). The later version is recommended, although maintenance-2.1.x has been tested on some older versions of OS/compiler combos. For general information, the details for each branch are:

- Branch: maintenance-2.2.x
    - Decentralized RTI
    - Java 21
    - Windows (Visual Studio 2022)
    - Ubuntu 22.04, 24.04
    - Rocky Linux 9.5
 - Branch: maintenance-2.1.x:
    - Decentralized RTI
    - Java 11
    - Windows (Visual Studio 2017, 2019, 2022)
    - Ubuntu 16.04, 18.04, 20.04
    - Rocky Linux 8.10
