### ISSUE TITLE
queryGALT returns unexpected exception

### ISSUE THREAD

**Issue by bergtwvd** [openlvc/portico#174]
Portico 2.1.0 / Evolved / Java.

Once joined and initialised, time constrained federate does a queryGALT to find out how much it can progress to catch up with the other (time regulating) federates (if any).  In this situation the federate is the first one to join and there are not other federates (yet). The value TimeQueryReturn.timeIsValid should be false in this case.
However, an unexpected exception is thrown:

`
hla.rti1516e.exceptions.RTIinternalError: Unknown exception received from RTI (class hla.rti1516e.exceptions.RTIinternalError) for queryGALT(): No response from RTI (null) for message type: QueryGalt
    at org.portico.impl.hla1516e.Rti1516eAmbassador.logException(Rti1516eAmbassador.java:5596)
    at org.portico.impl.hla1516e.Rti1516eAmbassador.queryGALT(Rti1516eAmbassador.java:4294)
    at kmlserver.Federate.requestInitialTimeAdvancementIf(Federate.java:199)
    at kmlserver.Federate.advanceTime(Federate.java:256)
    at kmlserver.Federate.runFederate(Federate.java:74)
    at kmlserver.KMLServer.start(KMLServer.java:68)
    at kmlserver.Main.main(Main.java:224)
`

**Comment by timpokorny** [comment]
Automatic Note: I am cleaning up old Github issues.

If this issue is still impacting you, please re-open the ticket for some hopefully timely attention this time :(

**General Note**
I have been working to try and consolidate the current state of the repo. Specifically, to set up two longer term maintenance branches. I will shortly do two releases off these branches (2.2.0 and 2.1.3). The later version is recommended, although maintenance-2.1.x has been tested on some older versions of OS/compiler combos. For general information, the details for each branch are:

- Branch: maintenance-2.2.x
    - Decentralized RTI
    - Java 21
    - Windows (Visual Studio 2022)
    - Ubuntu 22.04, 24.04
    - Rocky Linux 9.5
 - Branch: maintenance-2.1.x:
    - Decentralized RTI
    - Java 11
    - Windows (Visual Studio 2017, 2019, 2022)
    - Ubuntu 16.04, 18.04, 20.04
    - Rocky Linux 8.10
