### ISSUE TITLE
NullPointerException on joinFederationExecution

### ISSUE THREAD

**Issue by sharpplayer** [openlvc/portico#177]
```
at org.portico.impl.hla1516e.Rti1516eAmbassador.logException(Rti1516eAmbassador.java:5595)
at org.portico.impl.hla1516e.Rti1516eAmbassador.joinFederationExecution(Rti1516eAmbassador.java:693)

```
This is due to `ModelMerger.validate() ` receiving a null model.  This is ultimately due to:
`ModelMerger.mergeDryRun( ObjectModel base, List<ObjectModel> extensions )` receiving a base value null from `joinFederateExecution`, which is because `federation.getManifest().getFom()` returns null for some reason.  This seemed to work in 2.0.2.

**Comment by sharpplayer** [comment]
Found out what was causing this...we were joining a federation before creating it.  I think before this just used to raise an exception something like "FederationDoesntExist" and we would just retry...but now we don't get that far.  By ensuring the federation is created before joining, we do not get this exception.

**Comment by sharpplayer** [comment]
By the way, if it helps, our two federates were running in the same process on different threads.  I have not tried this scenario with two feds in different processes, so could not confirm if the order is important there too.

**Comment by timpokorny** [comment]
Which call were you using? This should not happen. At worst an `RTIinternalError` should be called. There are tests to catch this use case, but perhaps they are not covering all the join call variants.

**Comment by sharpplayer** [comment]
Sorry for the delay...I am using:
`rtiamb.joinFederationExecution(federateName, federateType, federationName, joinMods);`
Where joinMods is an empty array (ie not null)

**Comment by timpokorny** [comment]
Closing out. I believe this has been fixed. Please reopen if still impacting.
