### ISSUE TITLE
Pacer federate faults on OwnershipAcquiredIncomingHandler

### ISSUE THREAD

**Issue by bergtwvd** [openlvc/portico#203]
I have a pacer federate A to pace time and that does not subscribe on anything.

Yet it faults on an acquire ownership from federate B for an object instance attribute from a third federate C.

Portico version: nightly-20160528

Trace:
````
pacer_1    | WARN  [main] portico.lrc: Can't change owner of attributes [616] to [DamageSim]: object unknown or undiscovered
pacer_1    | ERROR [main] portico.lrc: FAILURE Exception encountered while processing incoming message: null
pacer_1    | java.lang.NullPointerException
pacer_1    |    at org.portico.lrc.services.ownership.handlers.incoming.OwnershipAcquiredIncomingHandler.changeOwnership(OwnershipAcquiredIncomingHandler.java:119)
pacer_1    |    at org.portico.lrc.services.ownership.handlers.incoming.OwnershipAcquiredIncomingHandler.process(OwnershipAcquiredIncomingHandler.java:87)
pacer_1    |    at org.portico.utils.messaging.MessageChain.process(MessageChain.java:78)
pacer_1    |    at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
pacer_1    |    at org.portico.lrc.LRC.tickProcess(LRC.java:688)
pacer_1    |    at org.portico.lrc.LRC.tick(LRC.java:555)
pacer_1    |    at org.portico.impl.hla1516e.Impl1516eHelper.evokeMultiple(Impl1516eHelper.java:188)
pacer_1    |    at org.portico.impl.hla1516e.Rti1516eAmbassador.evokeMultipleCallbacks(Rti1516eAmbassador.java:5407)
pacer_1    |    at base.BaseFederate.evokeCallbacks(BaseFederate.java:69)
pacer_1    |    at pacer.Federate.processEvents(Federate.java:315)
pacer_1    |    at pacer.Federate.start(Federate.java:208)
pacer_1    |    at base.BaseApplication.start(BaseApplication.java:108)
pacer_1    |    at pacer.Pacer.main(Pacer.java:85)
````

**Comment by timpokorny** [comment]
**Template reply**: I am cleaning up older issues, especially those open a long time. If you posted this, please forgive how tardy I have been on responding. If you still use or need Portico, I will shortly do two releases (`2.2.0` and `2.1.3`) on these branches and I suggest sticking to the maintenance branches for now, ideally `maintenance-2.2.x` (although `maintenance-2.1.x` has been tested on some older versions of OS/compiler combos). 

For general information, the details for each branch are:

 - Branch: `maintenance-2.2.x`
   - Decentralized RTI
   - Java 21
   - Windows (VIsual Studio 2022)
   - Ubuntu 22.04, 24.04
   - Rocky Linux 9.5
 - Branch: `maintenance-2.1.x`:
   - Decentralized RTI
   - Java 11
   - Windows (Visual Studio 2017, 2019, 2022)
   - Ubuntu 16.04, 18.04, 20.04
   - Rocky Linux 8.10
