### ISSUE TITLE
Federate unable to join 1516e federation. NPE when merging modules

### ISSUE THREAD

**Issue by threadedblue** [openlvc/portico#205]
In ModelMerger line 609,

`public static void mergeDryRun( ObjectModel base, List<ObjectModel> extensions )...`

The parameter "base" is null causing an NPE to be thrown at line 99:
```
98		if( extension.getObjectRoot() != null )
99			mergeObjectClass( base.getObjectRoot(), extension.getObjectRoot() );
```
It would appear the root of this problem is that Manifest.federate is not being set anywhere that I can see.  After all, the aforementioned parameter "base" is ultimately read from the Manifest.

**How is this value supposed to be populated? Do I need to do something more?**   I believe I am following the Example correctly.

My setup is of two federates.  The first creates the federation then joins it.  I pass in a fom array at create time.  To wit:

```
rtiAmbassador.connect(federationAmbassador, CallbackModel.HLA_EVOKED);
rtiAmbassador.createFederationExecution(federationName, getFoms()); 
// Parameters are indeed valid
```

The second federate then simply joins also with a valid fom array:

`rtiAmbassador.joinFederationExecution(getFederateName(), getFederationName(), foms);
`

Error message:
```
hla.rti1516e.exceptions.RTIinternalError: Unknown exception received from RTI (class java.lang.NullPointerException) for joinFederationExecution(): null
	at org.portico.impl.hla1516e.Rti1516eAmbassador.logException(Rti1516eAmbassador.java:5605) ~[portico-2.1.0.jar:?]
	at org.portico.impl.hla1516e.Rti1516eAmbassador.joinFederationExecution(Rti1516eAmbassador.java:702) ~[portico-2.1.0.jar:?]
	at org.portico.impl.hla1516e.Rti1516eAmbassador.joinFederationExecution(Rti1516eAmbassador.java:614) ~[portico-2.1.0.jar:?]
	at iox.hla.ii.PubSubFederate.joinFederationExecution(PubSubFederate.java:411) [pubsub-federate-0.0.1.jar:?]
	at iox.hla.ii.PubSubFederate.init(PubSubFederate.java:132) [pubsub-federate-0.0.1.jar:?]
	at iox.hla.ii.SendMain.main(SendMain.java:35) [SendEMF-0.0.1.jar:?]
Caused by: java.lang.NullPointerException
	at org.portico.lrc.model.ModelMerger.merge(ModelMerger.java:101) ~[portico-2.1.0.jar:?]
	at org.portico.lrc.model.ModelMerger.mergeModels(ModelMerger.java:84) ~[portico-2.1.0.jar:?]
	at org.portico.lrc.model.ModelMerger.merge(ModelMerger.java:585) ~[portico-2.1.0.jar:?]
	at org.portico.lrc.model.ModelMerger.mergeDryRun(ModelMerger.java:645) ~[portico-2.1.0.jar:?]
	at org.portico.bindings.jgroups.JGroupsConnection.joinFederation(JGroupsConnection.java:247) ~[portico-2.1.0.jar:?]
	at org.portico.lrc.services.federation.handlers.outgoing.JoinFederationHandler.process(JoinFederationHandler.java:105) ~[portico-2.1.0.jar:?]
	at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187) ~[portico-2.1.0.jar:?]
	at org.portico.impl.hla1516e.Impl1516eHelper.processMessage(Impl1516eHelper.java:130) ~[portico-2.1.0.jar:?]
	at org.portico.impl.hla1516e.Rti1516eAmbassador.processMessage(Rti1516eAmbassador.java:5568) ~[portico-2.1.0.jar:?]
	at org.portico.impl.hla1516e.Rti1516eAmbassador.joinFederationExecution(Rti1516eAmbassador.java:656) ~[portico-2.1.0.jar:?]
	... 4 more
```

**Comment by timpokorny** [comment]
G'day @threadedblue, This is strange. Let's dig in a bit. In your `RTI.rid` file can you turn the logging up to `DEBUG` and post the output of the second federate that is generating the NPE?

There is a call in the [`JoinFederateHandler`](https://github.com/openlvc/portico/blob/master/codebase/src/java/portico/org/portico/lrc/services/federation/handlers/outgoing/JoinFederationHandler.java#L99) class that logs any additional FOM modules that it finds (shown below). I'd like to see what the [`JoinFederation`](https://github.com/openlvc/portico/blob/master/codebase/src/java/portico/org/portico/lrc/services/federation/msg/JoinFederation.java) request message thinks it has available.

```
89		// log the request and pass it on to the connection
90		logger.debug( "ATTEMPT Join federate ["+federate+"] to federation ["+federation+"]" );
91		
92		// parse any additional FOM modules and store back in the request for processing
93		if( request.getFomModules().size() > 0 )
94		{
95			for( URL fedLocation : request.getFomModules() )
96				request.addJoinModule( FomParser.parse(fedLocation) );
97			
98			// let people know what happened
99			logger.debug( "Parsed ["+request.getJoinModules().size()+"] additional FOM modules" );
100		}
```

**Comment by threadedblue** [comment]
Thanks for the response.  It seems I was confusing federationType with federationName when making the call to join the federation. I got it straight now.

Once again, thanks for the response.  It was helpful.
