### ISSUE TITLE
Using ServiceLoader with Portico

### ISSUE THREAD

**Issue by EMostafaAli** [openlvc/portico#206]
ServiceLoader is the standard way to load jar files (similar to the one used in RtiFactoryFactory which is disabled in Java 9 as in this issue #204 )

I tried to run this code (without adding Portico to the classpath which should work) but I got an exception.
```

File file = new File("C:/Program Files/Portico/portico-2.1.0/lib/portico.jar");
URL[] urls = new URL[]{file.toURI().toURL()};
URLClassLoader classLoader = new URLClassLoader(urls);
ServiceLoader<RtiFactory> load = ServiceLoader.load(RtiFactory.class, classLoader);
for (RtiFactory rtiFactory: load){
	RTIambassador rtiAmb = rtiFactory.getRtiAmbassador();
	rtiAmb.connect(new NullFederateAmbassador(), CallbackModel.HLA_IMMEDIATE);
	URL[] modules = new URL[]{
			(new File("Foms/Base.xml")).toURI().toURL()
	};
	rtiAmb.createFederationExecution("abc", modules);
	rtiAmb.joinFederationExecution("T1", "abc");
	rtiAmb.registerFederationSynchronizationPoint("Ready", null);
	System.out.println(rtiFactory.rtiName());
}
```
This is the exception

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.jgroups.conf.ConfiguratorFactory.getConfigStream(ConfiguratorFactory.java:151)
	at org.jgroups.conf.ConfiguratorFactory.getXmlConfigurator(ConfiguratorFactory.java:210)
	at org.jgroups.conf.ConfiguratorFactory.getStackConfigurator(ConfiguratorFactory.java:93)
	at org.jgroups.JChannel.<init>(JChannel.java:147)
	at org.portico.bindings.jgroups.channel.Channel.constructChannel(Channel.java:151)
	at org.portico.bindings.jgroups.channel.Channel.connect(Channel.java:124)
	at org.portico.bindings.jgroups.Federation.connect(Federation.java:122)
	at org.portico.bindings.jgroups.JGroupsConnection.findFederation(JGroupsConnection.java:205)
	at org.portico.bindings.jgroups.JGroupsConnection.joinFederation(JGroupsConnection.java:242)
	at org.portico.lrc.services.federation.handlers.outgoing.JoinFederationHandler.process(JoinFederationHandler.java:105)
	at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
	at org.portico.impl.hla1516e.Impl1516eHelper.processMessage(Impl1516eHelper.java:130)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.processMessage(Rti1516eAmbassador.java:5559)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.joinFederationExecution(Rti1516eAmbassador.java:652)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.joinFederationExecution(Rti1516eAmbassador.java:573)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.joinFederationExecution(Rti1516eAmbassador.java:549)
	at com.company.Main.main(Main.java:42)
Caused by: java.util.MissingResourceException: Can't find bundle for base name jg-messages, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1082)
	at org.jgroups.util.Util.<clinit>(Util.java:95)
	... 17 more
```

**Comment by timpokorny** [comment]
Hi @EMostafaAli - From a quick look around I am thinking this is a localization issue. Can you confirm the locale of the computer you are using this on? I believe `jg-messages` is a language localization properties file that one of the internal libraries use. I must be excluding it when I put Portico through it's "one-jar generation" process perhaps.

**Comment by EMostafaAli** [comment]
Thanks @timpokorny , The locale is English (United States).

I just want to emphasize that if I added portico to the class path, serviceloader works fine.

**Comment by timpokorny** [comment]
@EMostafaAli - I am in the process of updating the JGroups version to the latest. Hopefully that helps, but I'm not sure it will. For some reason the internal JGroups lookup doesn't seem to be aware of extensions in the custom classloader instance you are creating. 

Although it has moved since the version of JGroups Portico currently bundles, I suspect it is this line that is the culprit: https://github.com/belaban/JGroups/blob/master/src/org/jgroups/util/Util.java#L98

```
resource_bundle=ResourceBundle.getBundle("jg-messages",Locale.getDefault(),Util.class.getClassLoader());
```

That code is in a static block for the `Util` class. Looks like it is doing its lookup via the classload it was loaded with rather than the custom one being passed to the `ServiceLoader`. Not sure why they are different given that you don't reference anything Portico. Class loaders. When are they not a pain?

What's the core problem you are trying to solve? I wonder if there is a different approach that still works.

**Comment by EMostafaAli** [comment]
@timpokorny,  I have developed a [GUI](https://github.com/EMostafaAli/HlaListener) that can be used to send and receive calls from RTI. It was designed in a way that a user at runtime select a specific implementation of the standard (during development I used only the interfaces provided in the standard).

This approach is used to work fine with portico, pitch, and MAK using [this ](https://stackoverflow.com/questions/46694600/java-9-compatability-issue-with-classloader-getsystemclassloader) known hack.

Now, I am trying to move forward to java 9, but it looks anything but an easy task.

**Comment by timpokorny** [comment]
I do not envy that move!
