### ISSUE TITLE
ExampleFederate crashes with AttributeNotDefined exception

### ISSUE THREAD

**Issue by kwabenantim** [openlvc/portico#210]
In release 2.1.0, ExampleFederate crashes with the exception AttributeNotDefined.
The exception is thrown by rtiamb.publishObjectClassAttributes() from the following section:
```
this.sodaHandle = rtiamb.getObjectClassHandle( "HLAobjectRoot.Food.Drink.Soda" );
this.flavHandle = rtiamb.getAttributeHandle( sodaHandle, "Flavor" );
AttributeHandleSet attributes = rtiamb.getAttributeHandleSetFactory().create();
attributes.add( flavHandle );

rtiamb.publishObjectClassAttributes( sodaHandle, attributes );
```
However, attribute "Flavor" **is** defined for the Soda object class in the RestaurantDrinks FOM.
```
<objectClass>
    <name>Soda</name>
    <sharing>PublishSubscribe</sharing>
    <semantics>Carbonated beverage</semantics>
    <attribute>
        <name>Flavor</name>
        <dataType>FlavorType</dataType>
        <updateType>Conditional</updateType>
        <updateCondition>Customer request</updateCondition>
        <ownership>NoTransfer</ownership>
        <sharing>PublishSubscribe</sharing>
        <dimensions>
            <dimension>SodaFlavor</dimension>
            <dimension>BarQuantity</dimension>
        </dimensions>
        <transportation>HLAreliable</transportation>
        <order>TimeStamp</order>
        <semantics>Flavor of soda</semantics>
    </attribute>
</objectClass>
```

Trace:

```
ExampleFederate   : Created Federation
ExampleFederate   : Joined Federation as exampleFederate
FederateAmbassador: Successfully registered sync point: ReadyToRun
FederateAmbassador: Synchronization point announced: ReadyToRun
ExampleFederate   :  >>>>>>>>>> Press Enter to Continue <<<<<<<<<<

ExampleFederate   : Achieved sync point: ReadyToRun, waiting for federation...
FederateAmbassador: Federation Synchronized: ReadyToRun
ExampleFederate   : Time Policy Enabled
hla.rti1516e.exceptions.AttributeNotDefined: org.portico.lrc.compat.JAttributeNotDefined: PUBLISH-OBJECT: attribute [-1] not defined in object class [HLAobjectRoot.Food.Drink.Soda]
	at org.portico.impl.hla1516e.Rti1516eAmbassador.publishObjectClassAttributes(Rti1516eAmbassador.java:1161)
	at ieee1516e.ExampleFederate.publishAndSubscribe(ExampleFederate.java:404)
	at ieee1516e.ExampleFederate.runFederate(ExampleFederate.java:281)
	at ieee1516e.ExampleFederate.main(ExampleFederate.java:566)
Caused by: org.portico.lrc.compat.JAttributeNotDefined: PUBLISH-OBJECT: attribute [-1] not defined in object class [HLAobjectRoot.Food.Drink.Soda]
	at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:160)
	at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:108)
	at org.portico.lrc.services.object.data.InterestManager.publishObjectClass(InterestManager.java:619)
	at org.portico.lrc.services.pubsub.handlers.outgoing.PublishObjectClassHandler.process(PublishObjectClassHandler.java:110)
	at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
	at org.portico.impl.hla1516e.Impl1516eHelper.processMessage(Impl1516eHelper.java:130)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.processMessage(Rti1516eAmbassador.java:5559)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.publishObjectClassAttributes(Rti1516eAmbassador.java:1135)
	... 3 more
```

**Comment by kwabenantim** [comment]
Sorry, it appears this issue is a duplicate of #175
