### ISSUE TITLE
Error reading Variant data type

### ISSUE THREAD

**Issue by EMostafaAli** [openlvc/portico#214]
The attached FOM [Restaurant.zip](https://github.com/openlvc/portico/files/1565440/Restaurant.zip) throws the following error. The error is related to the variant data type. Please note this FOM is obtained from the standards.

```
hla.rti1516e.exceptions.ErrorReadingFDD: org.portico.lrc.compat.JErrorReadingFED: org.portico.lrc.compat.JConfigurationException: Element <alternative name="WaiterValue"> missing child <dataType> element
	at org.portico.impl.hla1516e.Rti1516eAmbassador.createFederationExecution(Rti1516eAmbassador.java:350)
	at ca.mali.Test.run1(Test.java:141)
	at ca.mali.Test.main(Test.java:59)
Caused by: org.portico.lrc.compat.JErrorReadingFED: org.portico.lrc.compat.JConfigurationException: Element <alternative name="WaiterValue"> missing child <dataType> element
	at org.portico.impl.hla1516e.fomparser.FOM.extractDatatypes(FOM.java:148)
	at org.portico.impl.hla1516e.fomparser.FOM.process(FOM.java:97)
	at org.portico.impl.hla1516e.fomparser.FOM.parseFOM(FOM.java:469)
	at org.portico.utils.fom.FomParser.parseFom(FomParser.java:109)
	at org.portico.utils.fom.FomParser.parse(FomParser.java:159)
	at org.portico.lrc.services.federation.handlers.outgoing.CreateFederationHandler.process(CreateFederationHandler.java:65)
	at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
	at org.portico.impl.hla1516e.Impl1516eHelper.processMessage(Impl1516eHelper.java:130)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.processMessage(Rti1516eAmbassador.java:5559)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.createFederationExecution(Rti1516eAmbassador.java:315)
	... 2 more
Caused by: org.portico.lrc.compat.JConfigurationException: Element <alternative name="WaiterValue"> missing child <dataType> element
	at org.portico.utils.fom.FedHelpers.getChildValue(FedHelpers.java:187)
	at org.portico.utils.fom.FedHelpers.extractVariantRecordTypes(FedHelpers.java:508)
	at org.portico.utils.fom.FedHelpers.extractDatatypes(FedHelpers.java:274)
	at org.portico.impl.hla1516e.fomparser.FOM.extractDatatypes(FOM.java:142)
	... 11 more
```

**Comment by michaelrfraser** [comment]
Hi there EMastafaAli,

Just letting you know I've seen this issue and intend to look at it soon! I'm fairly booked up to Christmas with work, so will attempt to look at it first thing in the New Year.

Michael

**Comment by timpokorny** [comment]
Closing as fixed. Confirmed in `maintenance-2.1.x` and `maintenance-2.2.x`.
