### ISSUE TITLE
HLAobjectRoot bug

### ISSUE THREAD

**Issue by EMostafaAli** [openlvc/portico#253]
I noticed that Portico gives the following exception if "HLAobjectRoot" is not defined in a class; although, this attribute should be merged automatically through the RTI.
I attached 2 Foms with and without the "HLAobjectRoot" for testing.

the exception
`hla.rti1516e.exceptions.AttributeNotDefined: org.portico.lrc.compat.JAttributeNotDefined: PUBLISH-OBJECT: attribute [-1] not defined in object class [HLAobjectRoot.Payroll]
	at org.portico.impl.hla1516e.Rti1516eAmbassador.publishObjectClassAttributes(Rti1516eAmbassador.java:1161)
	at ca.ualberta.construction.safety.FederateAmbassador.federationSynchronized(FederateAmbassador.java:70)
	at org.portico.impl.hla1516e.handlers.SyncAchievedCallbackHandler.process(SyncAchievedCallbackHandler.java:64)
	at org.portico.utils.messaging.MessageChain.process(MessageChain.java:78)
	at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
	at org.portico.lrc.LRC.tickProcess(LRC.java:688)
	at org.portico.lrc.LRC.access$100(LRC.java:106)
	at org.portico.lrc.LRC$ImmediateCallbackDispatcher.run(LRC.java:834)
Caused by: org.portico.lrc.compat.JAttributeNotDefined: PUBLISH-OBJECT: attribute [-1] not defined in object class [HLAobjectRoot.Payroll]
	at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:160)
	at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:108)
	at org.portico.lrc.services.object.data.InterestManager.publishObjectClass(InterestManager.java:619)
	at org.portico.lrc.services.pubsub.handlers.outgoing.PublishObjectClassHandler.process(PublishObjectClassHandler.java:110)
	at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
	at org.portico.impl.hla1516e.Impl1516eHelper.processMessage(Impl1516eHelper.java:130)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.processMessage(Rti1516eAmbassador.java:5559)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.publishObjectClassAttributes(Rti1516eAmbassador.java:1135)
	... 7 more
`

[SafetyUI.zip](https://github.com/openlvc/portico/files/1745303/SafetyUI.zip)

**Comment by timpokorny** [comment]
Hi @EMostafaAli, I wonder if this is related to some of the things that @michaelrfraser is fixing ATM. @michaelrfraser - once the examples are up and running again can you take a quick look at this one?

**Comment by timpokorny** [comment]
Closed as Fixed.
