### ISSUE TITLE
Invalid RTI file format in cpp example

### ISSUE THREAD

**Issue by guigui64** [openlvc/portico#321]
When running the cpp example:

```bash
$ cd examples/cpp/ieee1516e
$ ./linux64.sh compile
$ ./linux64.sh execute federateTwo
[Fatal Error] RTI.rid:1:1: Content is not allowed in prolog.
Connection failed, Generic Error: hla.rti1516e.exceptions.RTIinternalError: XML format error: Content is not allowed in prolog.
        at org.portico.impl.hla1516e.Impl1516eHelper.initialize(Impl1516eHelper.java:105)
        at org.portico.impl.hla1516e.Impl1516eHelper.connect(Impl1516eHelper.java:152)
        at org.portico.impl.hla1516e.Impl1516eHelper.connect(Impl1516eHelper.java:115)
        at org.portico.impl.hla1516e.Rti1516eAmbassador.connect(Rti1516eAmbassador.java:207)
        at org.portico.impl.cpp1516e.ProxyRtiAmbassador.connect(ProxyRtiAmbassador.java:192)
Caused by: org.portico.lrc.compat.JConfigurationException: XML format error: Content is not allowed in prolog.
        at org.portico2.common.utils.XmlUtils.parseXmlFile(XmlUtils.java:83)
        at org.portico2.common.configuration.RID.parseRid(RID.java:266)
        at org.portico2.common.configuration.RID.<init>(RID.java:98)
        at org.portico2.common.configuration.RID.loadRid(RID.java:451)
        at org.portico2.common.configuration.RID.loadRid(RID.java:395)
        at org.portico2.common.configuration.RID.loadRid(RID.java:491)
        at org.portico.impl.hla1516e.Impl1516eHelper.initialize(Impl1516eHelper.java:99)
        ... 4 more
Caused by: org.xml.sax.SAXParseException; systemId: file:/home/comte/workspaces/hla/portico/codebase/dist/portico-2.2.0/examples/cpp/ieee1516e/./RTI.rid; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
        at org.portico2.common.utils.XmlUtils.parseXmlFile(XmlUtils.java:79)
        ... 10 more

Something else happened: hla.rti1516e.exceptions.NotConnected: Federate has not yet called connect()
        at org.portico.impl.hla1516e.Impl1516eHelper.checkConnected(Impl1516eHelper.java:296)
        at org.portico.impl.hla1516e.Rti1516eAmbassador.processMessage(Rti1516eAmbassador.java:5867)
        at org.portico.impl.hla1516e.Rti1516eAmbassador.createFederationExecution(Rti1516eAmbassador.java:290)
        at org.portico.impl.hla1516e.Rti1516eAmbassador.createFederationExecution(Rti1516eAmbassador.java:424)
        at org.portico.impl.cpp1516e.ProxyRtiAmbassador.createFederationExecution(ProxyRtiAmbassador.java:248)

terminate called after throwing an instance of 'rti1516e::NotConnected'
Aborted (core dumped)
```

Indeed, the provided RTI.rid file is not an XML file.

**Comment by timpokorny** [comment]
Hello @guigui64 - I apologise! It has been so long since you asked your question.

I will shortly do two releases (`2.2.0` and `2.1.3`) on these branches and I suggest sticking to the maintenance branches for now, ideally `maintenance-2.2.x` (although `maintenance-2.1.x` has been tested on some older versions of OS/compiler combos). 

For general information, the details for each branch are:

 - Branch: `maintenance-2.2.x`
   - Decentralized RTI
   - Java 21
   - Windows (VIsual Studio 2022)
   - Ubuntu 22.04, 24.04
   - Rocky Linux 9.5
 - Branch: `maintenance-2.1.x`:
   - Decentralized RTI
   - Java 11
   - Windows (Visual Studio 2017, 2019, 2022)
   - Ubuntu 16.04, 18.04, 20.04
   - Rocky Linux 8.10

Hopefully that helps if you find yourself still needing Portico.
