### ISSUE TITLE
Java 11 issue

### ISSUE THREAD

**Issue by rmpt** [openlvc/portico#334]
I'm running Portico 2.1.0 on Java 11, wanrouter seems to be running fine.
I've setup my environment as described in the README file, with RTI_HOME and CLASSPATH variables, imported the portico.jar library into my java project but the problem happens when I try to connect (initialize really) a federate, I get the error:

```
Caused by: java.lang.IllegalArgumentException: hla.rti1516e.RtiFactory is not an ImageIO SPI class
	at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:722)
	at java.desktop/javax.imageio.spi.ServiceRegistry.lookupProviders(ServiceRegistry.java:207)
	at hla.rti1516e.RtiFactoryFactory.getRtiFactory(RtiFactoryFactory.java:44)
```
This happens when I call `RtiFactoryFactory.getRtiFactory()`.

From what I get with this error, it's something related with the java encode version, that seems to incompatible with the java version I'm using to develop a federate - 11.

How can I fix this?

**Comment by icemagno** [comment]
You can try my Docker solution. Focus on your Fed and let the Portico stuff with me.

**Comment by timpokorny** [comment]
@rmpt - Again, so much time has passed, but, this should be fixed on `maintenance-2.1.x` and `maintenance-2.2.x` now.
