### ISSUE TITLE
Java example not working - ieee1516e

### ISSUE THREAD

**Issue by rmpt** [openlvc/portico#335]
I'm trying to run example in `portico-2.1.0\examples\java\ieee1516e`, but it doesn't seem to work.

As mentioned in the README.txt, I start one federate, don't press enter when requested, and start another federate so they can interact. Once the second federate joins, I get this error:

```
DEBUG [main] portico.lrc: org.portico.lrc.compat.JAttributeNotDefined: PUBLISH-OBJECT: attribute [-1] not defined in object class [HLAobjectRoot.Food.Drink.Soda]
hla.rti1516e.exceptions.AttributeNotDefined: org.portico.lrc.compat.JAttributeNotDefined: PUBLISH-OBJECT: attribute [-1] not defined in object class [HLAobjectRoot.Food.Drink.Soda]
        at org.portico.impl.hla1516e.Rti1516eAmbassador.publishObjectClassAttributes(Rti1516eAmbassador.java:1161)
        at ieee1516e.ExampleFederate.publishAndSubscribe(ExampleFederate.java:403)
        at ieee1516e.ExampleFederate.runFederate(ExampleFederate.java:281)
        at ieee1516e.ExampleFederate.main(ExampleFederate.java:560)
Caused by: org.portico.lrc.compat.JAttributeNotDefined: PUBLISH-OBJECT: attribute [-1] not defined in object class [HLAobjectRoot.Food.Drink.Soda]
        at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:160)
        at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:108)
        at org.portico.lrc.services.object.data.InterestManager.publishObjectClass(InterestManager.java:619)
        at org.portico.lrc.services.pubsub.handlers.outgoing.PublishObjectClassHandler.process(PublishObjectClassHandler.java:110)
        at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
        at org.portico.impl.hla1516e.Impl1516eHelper.processMessage(Impl1516eHelper.java:130)
        at org.portico.impl.hla1516e.Rti1516eAmbassador.processMessage(Rti1516eAmbassador.java:5559)
        at org.portico.impl.hla1516e.Rti1516eAmbassador.publishObjectClassAttributes(Rti1516eAmbassador.java:1135)
```

Seems the attribute is not found in the described FOM or something, aldo, the -1 seems like some internal discover bug, that portico cannot find the indicated attribute for the specific class. I've experienced the exact same error with another FOM file.

**Comment by timpokorny** [comment]
Cleaning up the issue log. @rmpt - so much time has passed, but this should be fixed now on the maintenance branches. All the example federates should now work on those branches.

I will shortly do two releases (`2.2.0` and `2.1.3`) on these branches and I suggest sticking to the maintenance branches for now, ideally `maintenance-2.2.x` (although `maintenance-2.1.x` has been tested on some older versions of OS/compiler combos). 

For general information, the details for each branch are:

 - Branch: `maintenance-2.2.x`
   - Decentralized RTI
   - Java 21
   - Windows (VIsual Studio 2022)
   - Ubuntu 22.04, 24.04
   - Rocky Linux 9.5
 - Branch: `maintenance-2.1.x`:
   - Decentralized RTI
   - Java 11
   - Windows (Visual Studio 2017, 2019, 2022)
   - Ubuntu 16.04, 18.04, 20.04
   - Rocky Linux 8.10

Hopefully that helps!
