### ISSUE TITLE
Sporadic exceptions when federates are resigning

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#54]
Summary
--------------
While building the WAN test federate to validate some behaviour for the site-connector functionality currently being added I have noticed that sporadically exceptions will be encountered during the resign process. 

From the exceptions, it looks to be happening when a remote federate receives a resignation (or some other message close to that event in the test federate code), not anything on the active federate end. However, I'm not certain of that.

These exceptions are always the same basic problem: `Error processing received message: null`. Perhaps there is a race condition happening and by the time a receiving federate attempts to process the message, the subject is gone and there is no null check. Or, it could be that a resigning federate has its infrastructure reset and then before it has a chance to shut down its receivers it gets a message it is not prepared to handle at that point in time.

Further investigation required. Two example stack traces included below:

```
INFO  [main] wantest: Resigned from Federation
ERROR [Incoming,WAN Test Federation,zapp-10678] portico.lrc.jgroups: Error processing received message: null
java.lang.NullPointerException
	at org.portico.bindings.jgroups.MessageReceiver.receiveAsynchronous(MessageReceiver.java:81)
	at org.portico.bindings.jgroups.channel.FederationListener.receive(FederationListener.java:246)
	at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.handleUpEvent(MessageDispatcher.java:528)
	at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.up(MessageDispatcher.java:606)
	at org.jgroups.JChannel.up(JChannel.java:715)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:1020)
	at org.jgroups.protocols.pbcast.FLUSH.up(FLUSH.java:504)
	at org.jgroups.protocols.pbcast.STATE_TRANSFER.up(STATE_TRANSFER.java:178)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:181)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:400)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:418)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:896)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:244)
	at org.jgroups.protocols.RSVP.up(RSVP.java:188)
	at org.jgroups.protocols.UNICAST2.up(UNICAST2.java:432)
	at org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:754)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:570)
	at org.jgroups.protocols.BARRIER.up(BARRIER.java:126)
	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:143)
	at org.jgroups.protocols.FD_ALL.up(FD_ALL.java:177)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:290)
	at org.jgroups.protocols.Discovery.up(Discovery.java:359)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1293)
	at org.jgroups.protocols.TP$IncomingPacket.handleMyMessage(TP.java:1856)
	at org.jgroups.protocols.TP$IncomingPacket.run(TP.java:1824)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```
INFO  [main] wantest:   5|++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ 
INFO  [main] wantest:    |--|--|--|--| 5|--|--|--|--|10|--|--|--|--|15|--|--|--|--|20|
WARN  [main] portico.lrc: MOM support is currently unsupported in IEEE-1516e federations.
ERROR [Incoming,WAN Test Federation,zapp-46900] portico.lrc.jgroups: Error processing received message: null
java.lang.NullPointerException
	at org.portico.bindings.jgroups.MessageReceiver.receiveAsynchronous(MessageReceiver.java:81)
	at org.portico.bindings.jgroups.channel.FederationListener.receive(FederationListener.java:246)
	at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.handleUpEvent(MessageDispatcher.java:528)
	at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.up(MessageDispatcher.java:606)
	at org.jgroups.JChannel.up(JChannel.java:715)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:1020)
	at org.jgroups.protocols.pbcast.FLUSH.up(FLUSH.java:504)
	at org.jgroups.protocols.pbcast.STATE_TRANSFER.up(STATE_TRANSFER.java:178)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:181)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:400)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:418)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:896)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:244)
	at org.jgroups.protocols.RSVP.up(RSVP.java:188)
	at org.jgroups.protocols.UNICAST2.up(UNICAST2.java:432)
	at org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:754)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:570)
	at org.jgroups.protocols.BARRIER.up(BARRIER.java:126)
	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:143)
	at org.jgroups.protocols.FD_ALL.up(FD_ALL.java:177)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:290)
	at org.jgroups.protocols.Discovery.up(Discovery.java:359)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1293)
	at org.jgroups.protocols.TP$5.run(TP.java:1211)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
 
Environment and Logs
-------------------------------
 * Portico v2.0.1
 * Wan test federate (`ieee1516e`)
 * Ubuntu 14.04LTS (VM - Digital Ocean)
 
Reproduction Steps
----------------------------
Observed at random times while running the WAN test federate. I was not able to uncover a repeatable process, but the problem was reasonably frequent.

**Comment by timpokorny** [comment]
**NOTE** While performing some unrelated work I noticed that when this happens for a given federate, the other federates begin to report JGroups errors about a crashed member (`VERIFY_SUSPECT` messages) indicating that JGroups has noticed a federate has prematurely dies and is trying to figure out if it really is gone to determine whether it should be kicked from the group.
