### ISSUE TITLE
Portico zero's out bytes when trying to send large attribute/parameter values

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#65]
I've had two reports now that indicate there is a problem when trying to transfer large parameter/attributes values, after a certain point, bytes begin to get zero'd out. 

According to [this report](http://forums.porticoproject.org/viewtopic.php?t=328) on the forums, when trying to send 1024-byte updates, bytes from index 987 onward are zero'd out (while 986 and below are correct):

> Using the example federation i tried to exchange an Object that consists of one single attribute of 1024 Bytes length. When this attribute is reflected only the values of bytes 0 to 986 are correct, bytes 987 to 1024 have value zero. If I add an additional attribute of size 16 byte in front of the 1024 attribute, then I get zeros already at byte 963 which means 23 more zeros. Is there a limitation for the length of an Object or attribute?

I've also had a report from Anthony Cramp, who provide some log files showing the problem (attached). The files he provided are:

 * A log file showing the problem
 * The modified versions of the message handlers that were used
 * Support class used for serialization/deserialization

**UPDATE**
I now have a test that reproduces this problem. I'm about to check it in to the HLA 1.3 `ReflectAttributesTest}`

```java
@Test(groups="jgroups")
public void testROUpdateWithLargeAttributeValue()
{
    byte[] sent1024 = new byte[1024];
    Random random = new Random();
    random.nextBytes( sent1024 );
    
    // package this into an update and sent it from the sender to the receiver
    Map<String,byte[]> updatedAttributes = new HashMap<String,byte[]>();
    updatedAttributes.put( "aa", sent1024 );
    defaultFederate.quickReflect( objectHandle, updatedAttributes, null );
    
    // validate that the values reach the other side ok
    secondFederate.fedamb.waitForROUpdate( objectHandle );
    Test13Instance temp = secondFederate.fedamb.getInstances().get( objectHandle );
    
    // ensure that it has all the appropriate values
    byte[] received1024 = temp.getAttributeValue( aaHandle );
    assertNotNull( received1024, "did not receive update for correct attribute" );
    assertEquals( received1024.length, 1024, "received wrong number of bytes in update" );
    for( int i = 0; i < 1024; i++ )
    {
        assertEquals( received1024[i], sent1024[i], "byte at ["+i+"] was incorrect" );
    }
}
```

This generates the following error:

```
java.lang.AssertionError: byte at [989] was incorrect expected:<84> but was:<0>
	at hlaunit.hla13.object.ReflectAttributesTest.testROUpdateWithLargeAttributeValue(ReflectAttributesTest.java:213)
```

This only shows up when using the JGroups binding. With the JVM binding, the test seems to pass happily. Further investigation underway.

**Comment by timpokorny** [comment]
Note received via email from user:

> I struggled about the same issue, and might found the origin as well as a workaround or a maybe a solution. It seems to be located in the UpdateAttributes class at line 221.
> 
> The `buffer.read( attributeValue, 0, valueSize );` expression reads only 986 bytes even if `valueSize > 986`. Changing the line to `buffer.readFully(attributeValue);` seems to work fine for me.

Need to change and check whether fix also works for us.

**Comment by 314314314** [comment]
I don't know if this is related, when I try to send a interaction with large parameters (>800 bytes), the receiving side (not necessarily subscribed to that interaction) throws the following error.
```
ERROR [Incoming,CyberPhys,PC-6] portico.lrc.jgroups: Error proces
sing received message: couldn't convert byte[] into PorticoMessage
java.lang.RuntimeException: couldn't convert byte[] into PorticoMessage
        at org.portico.lrc.utils.MessageHelpers.inflate(MessageHelpers.java:222)
        at org.portico.bindings.jgroups.MessageReceiver.receiveAsynchronous(MessageReceiver.java:73)
        at org.portico.bindings.jgroups.channel.FederationListener.receive(FederationListener.java:246)
        at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.handleUpEvent(MessageDispatcher.java:528)
        at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.up(MessageDispatcher.java:606)
        at org.jgroups.JChannel.up(JChannel.java:715)
        at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:1020)
        at org.jgroups.protocols.pbcast.FLUSH.up(FLUSH.java:504)
        at org.jgroups.protocols.pbcast.STATE_TRANSFER.up(STATE_TRANSFER.java:178)
        at org.jgroups.protocols.FRAG2.up(FRAG2.java:181)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:400)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:418)
        at org.jgroups.protocols.pbcast.GMS.up(GMS.java:896)
        at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:244)
        at org.jgroups.protocols.RSVP.up(RSVP.java:188)
        at org.jgroups.protocols.UNICAST2.up(UNICAST2.java:432)
        at org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:754)
        at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:570)
        at org.jgroups.protocols.BARRIER.up(BARRIER.java:126)
        at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:143)
        at org.jgroups.protocols.FD_ALL.up(FD_ALL.java:177)
        at org.jgroups.protocols.MERGE3.up(MERGE3.java:290)
        at org.jgroups.protocols.Discovery.up(Discovery.java:359)
        at org.jgroups.protocols.TP.passMessageUp(TP.java:1293)
        at org.jgroups.protocols.TP$IncomingPacket.handleMyMessage(TP.java:1856)
        at org.jgroups.protocols.TP$IncomingPacket.run(TP.java:1829)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readInt(Unknown Source)
        at java.io.ObjectInputStream$BlockDataInputStream.readInt(Unknown Source)
        at java.io.ObjectInputStream.readInt(Unknown Source)
        at org.portico.lrc.services.object.msg.SendInteraction.unmarshal(SendInteraction.java:239)
        at org.portico.lrc.utils.MessageHelpers.manuallyUnmarshal(MessageHelpers.java:251)
        at org.portico.lrc.utils.MessageHelpers.inflate(MessageHelpers.java:206)

        ... 28 more

```

There appeared to be an unexpected termination of data stream, leading to an EOF exception in JGroup. 

Settings:
OS: Win7
Portico version: 2.0.0, 2.0.1

**Comment by timpokorny** [comment]
G'day mate - I suspect this is related but I think the EOF exception is due to the under flow of bytes rather than the root cause of it unfortunately :( Still digging around atm

**Comment by timpokorny** [comment]
Looking at this, switching the method call from `read(byte[],offset,len)` to `readFully(byte[])` does seem to fix the problem, however I have no idea why!

Diving into the standard library code it looks like the difference is that `read(byte[],offset,len)` will operate in a block-read mode if supported, allowing it to read data in chunks (989 in this instance by the looks of it). `readFully(byte[])` however just keeps calling `read()` (returning a single byte) until the buffer is full. 

This is frustrating at the moment because I can't see the reason for this (with my tired eyes), but my concern is that the basic `readFully()` will be slower than the block-mode operating  version because it has to get every byte, every time.

More investigation needed when I'm awake again!

**Comment by timpokorny** [comment]
Looks like my tired reading was totally wrong and calling `readFully()` just loops back to the same block-mode `read()` call, so should be no performance issues. Fixed!

Have updated `master` and `maintenance-2.0.1`.
