### ISSUE TITLE
Portico cannot keep up with object create messages in high-traffic environment

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#74]
Summary
----
Stack traces are being reported from a user who is registering a _lot_ of objects (and doing it quickly). 

> When registering more than around 10,000 object instances the following error message appears:
> 
> ERROR [AWT-EventQueue-0] portico.lrc: org.portico.lrc.compat.JRTIinternalError: Problem sending message: channel=SEMSim, error message=Task org.jgroups.protocols.TP$5@2e95db03rejected from java.util.concurrent.ThreadPoolExecutor@45d6ff96[Running, pool size = 10, active threads = 1, queued tasks = 1000, completed tasks = 11782]
> 
> It seems that items of the internal queue with the size 1000 cannot be polled fast enough. Registering new object instances is faster than processing items of this queue making it grow until around 10,000 items (11,782 in this example but this number varies in each execution). 
> 
> We helped ourselves in just letting our pushing thread wait for a couple of milliseconds and retry registering object instances. This way we were able to register around 200,000 object instances. But it seems that there is no way of configuring the queue size in the RTI.rid file. Is there any other workaround for this problem, maybe increasing the queue size?

_via email from David Ciechanowicz, TUM Create, testing with Portico on large traffic simulator_

Environment and Logs
----
 - Portico `v2.0.0`
 - Windows 7 SP1 64-bit w/Java 1.8
 
Reproduction Steps
----
 1. Create a truck-load of objects quickly
 2. Watch the logs for the crashy

**Comment by timpokorny** [comment]
Full stack trace from recent run:

```
ERROR [main] portico.lrc: org.portico.lrc.compat.JRTIinternalError: Problem sending message: channel=WAN Test Federation, error message=Task org.jgroups.protocols.TP$5@308e87a1 rejected from java.util.concurrent.ThreadPoolExecutor@66298fe9[Running, pool size = 10, active threads = 2, queued tasks = 1000, completed tasks = 425136]
Exception in thread "main" hla.rti1516e.exceptions.RTIinternalError: org.portico.lrc.compat.JRTIinternalError: Problem sending message: channel=WAN Test Federation, error message=Task org.jgroups.protocols.TP$5@308e87a1 rejected from java.util.concurrent.ThreadPoolExecutor@66298fe9[Running, pool size = 10, active threads = 2, queued tasks = 1000, completed tasks = 425136]
	at org.portico.impl.hla1516e.Rti1516eAmbassador.updateAttributeValues(Rti1516eAmbassador.java:2081)
	at wantest.throughput.ThroughputDriver.loop(ThroughputDriver.java:309)
	at wantest.throughput.ThroughputDriver.execute(ThroughputDriver.java:135)
	at wantest.Federate.execute(Federate.java:121)
	at wantest.Main.main(Main.java:49)
Caused by: org.portico.lrc.compat.JRTIinternalError: Problem sending message: channel=WAN Test Federation, error message=Task org.jgroups.protocols.TP$5@308e87a1 rejected from java.util.concurrent.ThreadPoolExecutor@66298fe9[Running, pool size = 10, active threads = 2, queued tasks = 1000, completed tasks = 425136]
	at org.portico.bindings.jgroups.channel.FederationChannel.send(FederationChannel.java:252)
	at org.portico.bindings.jgroups.JGroupsConnection.broadcast(JGroupsConnection.java:153)
	at org.portico.lrc.services.object.handlers.outgoing.UpdateAttributesHandler.process(UpdateAttributesHandler.java:105)
	at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
	at org.portico.impl.hla1516e.Impl1516eHelper.processMessage(Impl1516eHelper.java:99)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.processMessage(Rti1516eAmbassador.java:5554)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.updateAttributeValues(Rti1516eAmbassador.java:2063)
	... 4 more
Caused by: java.util.concurrent.RejectedExecutionException: Task org.jgroups.protocols.TP$5@308e87a1 rejected from java.util.concurrent.ThreadPoolExecutor@66298fe9[Running, pool size = 10, active threads = 2, queued tasks = 1000, completed tasks = 425136]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at org.jgroups.protocols.TP.down(TP.java:1209)
	at org.jgroups.protocols.Discovery.down(Discovery.java:576)
	at org.jgroups.protocols.FD_ALL.down(FD_ALL.java:201)
	at org.jgroups.protocols.VERIFY_SUSPECT.down(VERIFY_SUSPECT.java:80)
	at org.jgroups.protocols.BARRIER.down(BARRIER.java:94)
	at org.jgroups.protocols.pbcast.NAKACK2.send(NAKACK2.java:673)
	at org.jgroups.protocols.pbcast.NAKACK2.down(NAKACK2.java:453)
	at org.jgroups.protocols.UNICAST2.down(UNICAST2.java:523)
	at org.jgroups.protocols.RSVP.down(RSVP.java:143)
	at org.jgroups.protocols.pbcast.STABLE.down(STABLE.java:328)
	at org.jgroups.protocols.pbcast.GMS.down(GMS.java:965)
	at org.jgroups.protocols.FlowControl.down(FlowControl.java:351)
	at org.jgroups.protocols.MFC.handleDownMessage(MFC.java:116)
	at org.jgroups.protocols.FlowControl.down(FlowControl.java:341)
	at org.jgroups.protocols.FRAG2.down(FRAG2.java:147)
	at org.jgroups.protocols.pbcast.STATE_TRANSFER.down(STATE_TRANSFER.java:238)
	at org.jgroups.protocols.pbcast.FLUSH.down(FLUSH.java:312)
	at org.jgroups.stack.ProtocolStack.down(ProtocolStack.java:1025)
	at org.jgroups.JChannel.down(JChannel.java:729)
	at org.jgroups.JChannel.send(JChannel.java:445)
	at org.portico.bindings.jgroups.channel.FederationChannel.send(FederationChannel.java:247)
	... 10 more
```
