### ISSUE TITLE
NPE when Portico attempts to callback for failed sync point registration

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#83]
Summary
----
_As registered by Jeremy Coulon on the Portico Users mailing list_

When attempting to run two copies of the example federate, the second one prints out an exception after pressing Enter the first time

```
java.lang.NullPointerException at org.portico.impl.cpp1516e.ProxyFederateAmbassador.synchronizationPointRegistrationFailedProxyFederateAmbassador.java:170)
    at org.portico.impl.hla1516e.handlers.SyncRegResultCallbackHandler.process(SyncRegResultCallbackHandler.java:70)
    at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
    at org.portico.lrc.LRC.tickProcess(LRC.java:678)
    at org.portico.lrc.LRC.tick(LRC.java:547)
    at org.portico.impl.hla1516e.Impl1516eHelper.evokeMultiple(Impl1516eHelper.java:157)
    at org.portico.impl.hla1516e.Rti1516eAmbassador.evokeMultipleCallbacks(Rti1516eAmbassador.java:5402)
    at org.portico.impl.cpp1516e.ProxyRtiAmbassador.evokeMultipleCallbacks(ProxyRtiAmbassador.java:2127)
```

The second federate is attempting to register the already registered sync point and failing (as it should), but the callback is causing an NPE for some reason. Perhaps the sync point failure reason is null (as call `reason.name()` on it, which would cause this if it were null).
 
What I'm trying to do
----
Run two copies of the example federate.

Steps to Reproduce
----
Step to reproduce:
 1. Win32-vc10.bat compile
 1. Win32-vc10.bat execute fed1
 1. Win32-vc10.bat execute fed2
 1. Press Enter on 1st federate
 1. Press Enter on 2nd federate

Note that behaviour changes whether I press Enter first on fed1 or fed2.
One of the federate also crash randomly when closing.

**Comment by timpokorny** [comment]
This looks to be fixed in `maintenance-2.1.x` and `maintenance-2.2.x`. Should be part of `portico-2.1.3` and `portico-2.2.0` (if not present in earlier versions).
